releases:
  - name: frontend
    namespace: default
    chart: ./frontend
    values:
      - ./frontend/values.yaml

  - name: faculty
    namespace: default
    chart: ./faculty
    values:
      - ./faculty/values.yaml
  
  - name: config
    namespace: default
    chart: ./config
    values:
      - ./config/values.yaml

  
