apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: faculty
  template:
    metadata:
      labels:
        app: faculty
    spec:
      containers:
        - name: faculty
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
