apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty
  labels:
    {{- include "faculty.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "faculty.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "faculty.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: faculty
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
