apiVersion: v1
kind: Service
metadata:
  name: faculty
spec:
  type: {{ .Values.service.type }}
  selector:
    app: faculty
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
