apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eureka.fullname" . }}
  labels:
    app: {{ include "eureka.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "eureka.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "eureka.name" . }}
    spec:
      containers:
        - name: eureka
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8761
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
