apiVersion: v1
kind: Service
metadata:
  name: {{ include "eureka.fullname" . }}
  labels:
    app: {{ include "eureka.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "eureka.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8761
      protocol: TCP
